Address missing functionality in Enterprise RBAC PR
Kong/deck pull request #278
Opened 2021-02-26 00:09 UTC by rainest

Addresses two issues found during testing for #276:

- Adds `--rbac-resources-only` support to `deck reset`.
- Rejects endpoint permissions with no workspace.

2021-02-26 07:07 UTC, hbagdi requested changes
Thanks for reviewing the patch and going the extra mile to send a fix for the issues you had raised!

2021-02-26 07:07 UTC, hbagdi commented on cmd/reset.go
> +		false, "sync only the RBAC resources (Kong Enterprise only)")
Copy pasta: description of the flag needs an update.

2021-02-26 07:07 UTC, hbagdi commented on state/rbac_endpoint_permission.go
> +	}
Please remove this and instead add workspace as a required field in https://github.com/Kong/deck/blob/main/file/codegen/main.go.
While you are at it, could you also make RBAC role's name field to be always required?
Feel free to add stricter validation for fields that are always required for RBAC role and RBAC endpoint permission.

2021-02-26 18:27 UTC, rainest commented
Given that we're checking workspace and endpoint in bc46bb0, it seemed like we should remove the similar existing endpoint check in the original PR also, so ddccda0 removes both. Wasn't positive that was what you wanted.

Leading slash in delete issue is now also fixed by c967616

2021-02-27 15:39 UTC, hbagdi commented
Incorporated this with some cleanup in #278, hence closing this.
I've done my best to attribute commits correctly. Please let me know if I missed something.

2021-02-27 15:39 UTC, closed without merging