fix: populate missing 'enabled' service field from file
Kong/deck pull request #677
Opened 2022-05-09 20:46 UTC by GGabriele

2022-05-09 21:34 UTC, rainest approved these changes
For reference, https://github.com/Kong/kong/commit/1339494f9cfc8f08433db91a7ce29443ddbe2483

2022-05-09 21:35 UTC, rainest requested changes
Code :+1:, can you add a pending release changelog entry for this?

2022-05-09 22:25 UTC, hbagdi commented
Please add a test.

2022-05-10 09:00 UTC, GGabriele commented
> Code 👍, can you add a pending release changelog entry for this?

I still need to get used to that :( added now

> Please add a test.

done

2022-05-10 17:50 UTC, GGabriele commented on file/reader_test.go
> +		c.Upstreams[0].Targets[0].Target)
sounds good

https://github.com/Kong/deck/pull/677/commits/882c51342f41bad6570325a9683de47d3105b8db

2022-05-10 20:48 UTC, rainest approved these changes

2022-05-10 20:49 UTC, merged